services:
  # Backend API Service (Frontend deployed on Vercel)
  - type: web
    name: stock-market-prediction-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: API_HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: '["https://your-frontend.vercel.app", "http://localhost:3000"]'
      - key: DEBUG_MODE
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
