services:
  # Backend API Service
  - type: web
    name: stolckr-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: API_HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: DEBUG_MODE
        value: false
      - key: SECRET_KEY
        generateValue: true
        
  # Frontend Web Service  
  - type: web
    name: stolckr-frontend
    env: node
    region: ohio  
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BACKEND_URL
        fromService:
          type: web
          name: stolckr-backend
          property: host