name: Deploy Backend to Railway

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'backend/**'
      - 'nixpacks.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      run: railway up --detach
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        
    - name: Get deployment URL
      run: |
        echo "Backend deployed to Railway!"
        echo "Check your Railway dashboard for the URL"